// The original tf-rel-win pipeline

static final ArrayList buildLabels = [ 'winhrel' ]
static final String branchName = params.get('CHECKOUT_BRANCH', 'master')
static final String python_version = params.get('PYTHON_VERSION', 'all')
static final boolean upload_pypi = params.get('UPLOAD_PYPI', false)

def runBuild(pyVer) {
    catchError {
        withEnv(["WORKSPACE=$WORKSPACE","PYTHON_VERSION=${pyVer}","RELEASE_BUILD=1"]) {
            echo "----- Build TF Windows Wheels with Python Version ${pyVer} -----"
            bat'''
                echo Workspace is %WORKSPACE%
                cd %WORKSPACE%
                wget https://raw.githubusercontent.com/Intel-tensorflow/tensorflow/bani/win_ci_scripts/tensorflow/tools/ci_build/windows/cpu/pip/ci_run_build_test.sh -O ci_run_build_test.sh
                wget https://raw.githubusercontent.com/Intel-tensorflow/tensorflow/bani/win_ci_scripts/tensorflow/tools/ci_build/windows/cpu/pip/make_new_package_name.py -O make_new_package_name.py
                bash ./ci_run_build_test.sh --release_build --extra_test_flags "--test_env=TF2_BEHAVIOR=1" --project_name "tensorflow_cpu"
            '''
        }
    }
    
    dir("$WORKSPACE" + "/artifact") {
        archiveArtifacts artifacts: 'tensorflow_cpu*.whl, *.log', excludes: null
    }
    
    dir("$WORKSPACE") {
        bat'''
        if not exist "%WORKSPACE%\\artifacts_bak" mkdir %WORKSPACE%\\artifacts_bak
        copy %WORKSPACE%\\artifact\\*.whl %WORKSPACE%\\artifacts_bak
        '''
    }
}

def uploadPyPI(pyVer) {
    catchError {
        withEnv(["WORKSPACE=$WORKSPACE", "PYTHON_VERSION=${pyVer}"]) {
            echo "----- Finally, uploading TF Windows Wheels to PyPI under tensorflow-intel namespace -----"
            
            echo "----- generate run_pypi_upload.bat -----"
            dir("$WORKSPACE" + "/artifacts_bak") {
                sh '''#!/bin/bash -x
                echo "echo This is run_pypi_upload.bat executing..." > ./run_pypi_upload.bat
                echo "pip install wheel twine" >> ./run_pypi_upload.bat
                echo "python %WORKSPACE%\\make_new_package_name.py tensorflow_cpu tensorflow_intel" >> ./run_pypi_upload.bat
                echo "twine upload tensorflow_intel*.whl --non-interactive --disable-progress-bar --skip-existing" >> ./run_pypi_upload.bat
                '''
            }
            
            withCredentials([usernamePassword(credentialsId: 'PYPI_INTEL_SECRET', usernameVariable: 'TWINE_USERNAME', passwordVariable: 'TWINE_PASSWORD')]) {
                bat'''
                set TWINE_REPOSITORY_URL=https://upload.pypi.org/legacy/
                cd %WORKSPACE%\\artifacts_bak
                if not exist "%WORKSPACE%\\venv_py%PYTHON_VERSION%\\Scripts\\activate" exit /b 1
                
                %WORKSPACE%\\venv_py%PYTHON_VERSION%\\Scripts\\activate && %WORKSPACE%\\artifacts_bak\\run_pypi_upload.bat
                cd %WORKSPACE%
                rmdir /s /q %WORKSPACE%\\artifacts_bak
                echo Upload completed.
                '''
            }
        }
    }
}

Map parallelBuild = [:]
buildLabels.each { l ->
    parallelBuild += [
        "${l}": {
            node(l) {
                stage('Checkout') {
                    if (fileExists('./tensorflow/.git/HEAD')) {
                        sh 'cd tensorflow && git checkout .'
                    }
                    checkout([$class: 'GitSCM',
                    branches: [[name: branchName]],
                    doGenerateSubmoduleConfigurations: false, 
                    extensions: [[$class           : 'RelativeTargetDirectory',
                                  relativeTargetDir: 'tensorflow']],
                    submoduleCfg: [],
                    userRemoteConfigs: [[url: 'https://github.com/tensorflow/tensorflow']]])
                } // stage Checkout
                
                dir("$WORKSPACE") {
                    bat'''
                    if exist "%WORKSPACE%\\artifact" rmdir /s /q %WORKSPACE%\\artifact
                    if exist "%WORKSPACE%\\artifacts_bak" rmdir /s /q %WORKSPACE%\\artifacts_bak
                    '''
                }

                if(python_version == "all") {
                    // Build TensorFlow, create wheel with python3.7
                    stage('Build1') {
                        runBuild("37")
                    } // stage Build1
                    
                    // Build TensorFlow, create wheel with python3.8
                    stage('Build2') {
                        runBuild("38")
                    } // stage Build2
                    
                    // Build TensorFlow, create wheel with python3.9
                    stage('Build3') {
                        runBuild("39")
                    } // stage Build3
                    
                    // Build TensorFlow, create wheel with python3.10
                    stage('Build4') {
                        runBuild("310")
                    } // stage Build4
                } else {
                    // Build TensorFlow, create wheel with Py version passed as parameter
                    stage('BuildX') {
                        runBuild(python_version)
                    } // stage Build1
                }
                
                if(upload_pypi) {
                    stage('Upload_PyPI') {
                        // Now upload the wheels to PyPI under tf_nightly_intel namespace
                        if(python_version == "all") {
                            uploadPyPI("310")
                        } else {
                            uploadPyPI(python_version)
                        }
                    }
                }
            }
        }
    ]
}
parallel parallelBuild